# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a285170d6e35afd9a684acffd979ac245760fb11af2be79336a3bd1e8453e984e4e3bc27adcc088959f2e8e0bed11b381202a73d6fde2e8f93660f623a1d828a

test:
  secret_key_base: 61ca7668b2d248bcde0ba518365b880a7f79b7853e823fc36767eb102eb46ed4de740470eba46ff1b08299aae59fcfe2000ba9c465963ea2880d0043e48548d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
